### ISSUE TITLE
(1) Can't install, (2) Can't validate

### ISSUE THREAD

**Issue by aprilmintacpineda** [CircleCI-Public/terraform-orb#101]
**Orb Version**
circleci/terraform@3.2.1

I have the following code in my circle ci file

```yml
terraformation:
  executor: terraform/default
  steps:
    - attach_workspace:
        at: ~/project
    - aws-cli/setup:
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        region: ap-southeast-1
    - terraform/install:
        terraform_version: 1.6.3
    - run:
        name: TFVars
        command: |
          rm -rf terraform.tfvars
          touch terraform.tfvars
          //.. bunch of echoes that to terraform.tfvars like echo 'something = "something"' >> terraform.tfvars
          cat terraform.tfvars
    - terraform/init
    - terraform/validate
    - terraform/apply
```

I'm getting 2 errors here,

Here's the first one:
![image](https://github.com/CircleCI-Public/terraform-orb/assets/21032419/51f5e57b-5119-485a-a8ef-896b146c638a)

The 2nd one is when I remove the `terraform/install` step, I will get the following
![Screen Shot 2023-11-11 at 6 27 07 PM](https://github.com/CircleCI-Public/terraform-orb/assets/21032419/63f0c8a3-d168-4a6d-8aab-0e8efc141392)

I have tested these variables locally and when I run `terraform validate`, I don't get any errors.

The `variables.tf` file:

```tf
variable "project_name" {
  type = string
}

variable "stage" {
  type = string

  validation {
    condition     = contains(["development", "staging", "production"], var.stage)
    error_message = "Allowed values for stage are \"development\", \"staging\", and \"production\""
  }
}

variable "aws_region" {
  type = string
}

variable "hosted_zone_id" {
  type = string
}

variable "hosted_zone_name" {
  type = string
}

variable "images_server_subdomain" {
  type    = string
  default = ""
}

variable "cache_policy_id" {
  type = string
}

variable "origin_request_policy_id" {
  type = string
}
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by aprilmintacpineda** [comment]
I opted out of using this orb and instead used this:

```yaml
terraformation:
  machine:
    image: ubuntu-2004:202010-01
  steps:
    - attach_workspace:
        at: ~/project
    - run:
        name: Install terraform
        command: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform
          terraform --version
    - run:
        name: TFVars
        command: |
          rm -rf variables.tfvars
          touch variables.tfvars
          // ... setup tf vars
    - run:
        name: Terraform deployment
        command: |
          terraform init
          terraform apply
```

This works.
