### ISSUE TITLE
Command terraform/install requires sudo, which is missing

### ISSUE THREAD

**Issue by LaurentEscalier** [CircleCI-Public/terraform-orb#23]
**Orb Version**

1.2.0

**Describe the bug**

When using the terraform/install command to install a specific version of Terraform, the command fails executing `sudo mv terraform /usr/local/bin` with the following error: `/bin/sh: sudo: not found`.

**To Reproduce**

1. Use the `circleci/terraform@1.2.0` orb in your pipeline
2. Setup a job running with executor `terraform/default`
3. Add the `terraform/install` command to the job
4. Schedule a pipeline run
5. Observer your terraform job failing at the `terraform/install` step

**Expected behavior**

_EITHER_ The [`terraform/default` execution environment](https://hub.docker.com/r/hashicorp/terraform) is configured to support the execution of the `terraform/install` command.

_OR_ The [orb documentation](https://circleci.com/developer/orbs/orb/circleci/terraform#commands-install) mentions the additional steps required to prepare the execution environment for the execution of the `terraform/install` command. 

**Additional context**

```
version: 2.1

orbs:
  terraform: circleci/terraform@1.2.0

jobs:
  # Terraform
  deploy_infrastructure:
    executor: terraform/default
    working_directory: ~/my-repository/infrastructure
    steps:
      - attach_workspace:
          name: Attach workplace from previous job(s)
          at: ~/my-repository
      - terraform/install:
          terraform_version: 0.13.5
```

**Comment by gmemstr** [comment]
If you're leveraging the default executor, you likely don't need to install terraform as well - if you need a specific version, you should pass that through to the executor or use another Docker image :)

```yaml
version: 2.1

orbs:
  terraform: circleci/terraform@1.2.0

jobs:
  # Terraform
  deploy_infrastructure:
    executor:
      name: terraform/default
      image: hashicorp/terraform:0.13.5
    working_directory: ~/my-repository/infrastructure
    steps:
      - attach_workspace:
          name: Attach workplace from previous job(s)
          at: ~/my-repository

```
