### ISSUE TITLE
Terraform workspace is expected to exist

### ISSUE THREAD

**Issue by ghost** [CircleCI-Public/terraform-orb#3]
**Orb Version**
1.0.1

**Describe the bug**
The `terraform/plan` and `terraform/apply` (and probably other) jobs require the Terraform workspace to already exist prior to usage.

**To Reproduce**
Use the `terraform/plan` or `terraform/apply` job with a completely empty state and specify a workspace. The call to `terraform workspace select` will fail.

**Expected behavior**
The orb creates the workspace before trying to use it and doesn't throw an error.

**Additional context**
The current workaround I'm using is:

```yaml
    - terraform/init:
        path: XYZ
        backend_config: *backend_config_prd
    - run:
        name: Create Terraform workspace if it doesn't already exist
        command: terraform workspace list XYZ/ | egrep -q '\sWORKSPACE$' || terraform workspace new WORKSPACE XYZ/
    - terraform/apply:
        path: XYZ
        backend_config: *backend_config_prd
        workspace: WORKSPACE
```

Preferably I should be able to remove both the `terraform/init` (as `apply` and `plan` do that anyway) and the `run` blocks.
