### ISSUE TITLE
terraform init doesn't work with 1.0.3

### ISSUE THREAD

**Issue by mimozell** [CircleCI-Public/terraform-orb#47]
Error message: `Too many command line arguments. Did you mean to use -chdir?`
Usage:
```
- terraform/install:
    terraform_version: '1.0.3'
- terraform/init:
    path: environment/<<parameters.environment>>/stateful
```
![Screenshot 2021-07-29 at 13 15 13](https://user-images.githubusercontent.com/40452559/127482775-c82c1ba4-0777-4172-8fc6-880b310b7c60.png)
