### ISSUE TITLE
terraform/install Fails with /bin/sh: shasum: not found

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/terraform-orb#48]
**Orb Version**

circleci/terraform@2.1.0

**Describe the bug**

`terraform/install` fails with error `/bin/sh: shasum: not found`.

**To Reproduce**

With the following file as contents of 

```
version: 2.1

orbs:
  terraform: circleci/terraform@2.1.0

jobs:
  deploy-infrastructure:
    executor: terraform/default
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          # note that the version must be in quotes
          terraform_version: "0.14.11"
        
workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - deploy-infrastructure
```

**Expected behavior**

Expected behavior is that the terraform file would be installed at the specified version.

** Notes**

We have done the following to resolve, but 

```
apk add perl # to install the sha1sum binary
ln -s /usr/bin/sha1sum /usr/bin/shasum # to link the sha1sum to shasum
```

Which also results in failure (error: `shasum: applet not found`) at which point we felt it would be worthwhile to file a bug report as it seems that the hashicorp company's image may not support shasum.

I realize the larger issue here may be that there is no (or little) value in using the hashicorp Docker image (as provided by terraform/default) with `terraform/install`.

**Comment by dexcom-jason** [comment]
Changes need to made to the terraform/default docker image as well as this orb src code to resolve these issues.  This orb is for all intensive purposes "broken" when calling the terraform/default executor.
1.  perl-utils package needs to be installed in the docker image to provide the shasum binary being called in terraform/install. (apk add --no-cache perl-utils)
2. Sudo is being called to unzip the terraform zip package during terraform/install.  Sudo is not typically used in a docker image. 
 If sudo is required then the sudo package also needs to be installed in the docker image.  (apk add --no-cache sudo)
3. This orb is not compatible with Terraform version >15.0 (The orb will fail).  When changing directories in terraform version >15 the -chdir parameter is REQUIRED.  In order to work with current versions of terraform the following src changes need to be made.

Current /src/scripts/validate.sh contains:
```
terraform init -input=false -backend=false -no-color "$TF_PARAM_PATH"
terraform validate -no-color "$TF_PARAM_PATH"
```

This needs to be changed to:
```
terraform init -input=false -backend=false -no-color -chdir "$TF_PARAM_PATH"
terraform validate -no-color -chdir "$TF_PARAM_PATH"
```

I am not a contributor to this project so am just offering the fixes I have already identified with this orb.  Hopefully a contributor watching this issue can make the neccessary changes.

-Jason

**Comment by gmemstr** [comment]
Quick question -- is it common to install a tool in a Docker image dedicated to said tool? My advice would be to simply remove that install step and opt for the correct version of the Docker image (this would require opting out of the executor provided by the orb. For reasons currently unknown to me the parameter for that executor changes the entire image rather than specifying a specific image tag).

```yaml
jobs:
  deploy-infrastructure:
    docker: 
      - image: hashicorp/terraform@#Terraform version#
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          # note that the version must be in quotes
          terraform_version: "0.14.11"
```

> This orb is not compatible with Terraform version >15.0 (The orb will fail). When changing directories in terraform version >15 the -chdir parameter is REQUIRED. In order to work with current versions of terraform the following src changes need to be made.

See #46. This is being worked on :)

**Comment by cristian-rivera** [comment]
You are much better off going to https://hub.docker.com/r/hashicorp/terraform/tags and finding the image that matches the Terraform version you are using. Then in your config.yml use it as shown below in tandem with the orb. This solved most of my issues!

```
orbs:
  terraform: circleci/terraform@3.0.0

executors:
  default:
    working_directory: ~/src
    docker:
      - image: hashicorp/terraform:1.0.9

jobs:
  format:
    parameters:
      module:
        type: string
        default: staging
    executor: default
    steps:
      - checkout
      - terraform/init:
          path: "./<< parameters.module >>"
      - terraform/fmt:
          path: "./<< parameters.module >>"
```
