### ISSUE TITLE
Circle CI context environment variables not being interpolated in 3.0.0

### ISSUE THREAD

**Issue by wbreza** [CircleCI-Public/terraform-orb#51]
**Orb Version**
3.0.0

**Describe the bug**

It appears that starting in 3.0.0 of the orb Circle CI context variables are no longer being interpolated in both `backend-config` and `var` parameters

**To Reproduce**

1. Create a new Circle CI context with the following:
    - TF_RESOURCE_GROUP_NAME = <CUSTOM_VALUE>
    - TF_STORAGE_ACCOUNT_NAME = <CUSTOM_VALUE>
    - TF_CONTAINER_NAME = <CUSTOM_VALUE>
    - TF_KEY_NAME = <CUSTOM_VALUE>
 
 2. Reference your context variables in your job config:
 
 ```yaml
      - terraform/init:
          backend: true
          backend_config:
            "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
            storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
            container_name=${TF_CONTAINER_NAME}, \
            key=${TF_KEY_NAME}"
```
3. Execute your CircleCI workflow/job

**Expected behavior**

Circle CI context values should be interpolated before being executed in scripts.

**Actual behavior**

In our case we are using the Azure Storage account as backend remote state and are getting an error: `Failed to get existing workspaces: Error retrieving keys for Storage Account "${TF_STORAGE_ACCOUNT_NAME}"...`

Where the environment variables are not getting interpolated before script is executed

**Additional context**

I believe this all stems from the refactor of when the scripts were moved out from being inline to referenced shell scripts.  You are creating `TF_` variables for your script execution but the input of those variables is not interpolated and the environment variable notations are being sent in verbatim.

**Comment by neerajmandal** [comment]
Same

**Comment by BSamodien** [comment]
Troubling

**Comment by punkdata** [comment]
@wbreza Thanks for opening this issue and your great feedback. We'll investigate.

**Comment by mpraveenreddie** [comment]
Any updates on this issue? @punkdata

**Comment by wbreza** [comment]
@punkdata - Any updates on this issue?

**Comment by wbreza** [comment]
@punkdata - My team is in the process of creating our own custom orb.  We prefer to use external shell scripts as well and found a work around for the same string interpolation issue.  Seems like the environment variable mapping in Circle CI doesn't work as expected and doesn't interpolate environment variables that exists within the parameters.

As a work around we have setup a pre-script that manually exports the environment variables and then sources them into the scripts before the next steps.

Found reference from [Circle CI](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-shell-command) docs as well.

ex)
```yml
steps:
  - run:
      name: Setup Environment Variables
      command: |
        echo "export EXAMPLE_VAR_1=<< parameters.example-var-1>>" >> $BASH_ENV
        echo "export EXAMPLE_VAR_2=<< parameters.example-var-2 >>" >> $BASH_ENV
        source $BASH_ENV
  - run:
      name: Fancy things
      command: <<include(scripts/example-script.sh)>>
```

**Comment by punkdata** [comment]
> @punkdata - My team is in the process of creating our own custom orb. We prefer to use external shell scripts as well and found a work around for the same string interpolation issue. Seems like the environment variable mapping in Circle CI doesn't work as expected and doesn't interpolate environment variables that exists within the parameters.
> 
> As a work around we have setup a pre-script that manually exports the environment variables and then sources them into the scripts before the next steps.
> 
> Found reference from [Circle CI](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-shell-command) docs as well.
> 
> ex)
> 
> ```yaml
> steps:
>   - run:
>       name: Setup Environment Variables
>       command: |
>         echo "export EXAMPLE_VAR_1=<< parameters.example-var-1>>" >> $BASH_ENV
>         echo "export EXAMPLE_VAR_2=<< parameters.example-var-2 >>" >> $BASH_ENV
>         source $BASH_ENV
>   - run:
>       name: Fancy things
>       command: <<include(scripts/example-script.sh)>>
> ```

@KyleTryon @gmemstr can either of you take a look at @wbreza suggestion? I will not be able to hack on this for some time and this needs some love.

@wbreza thank you for the suggestions.

**Comment by MohamedAnouar** [comment]
I can confirm that I had the same bug when I tried using the var section. 
Simple example : 
      - terraform/apply:
          attach-workspace: true
          context: terraform
          workspace: prod
          var: IMAGE_TAG=${CIRCLE_SHA1}
The variable IMAGE_TAG wasn't interpolated and the variable that was retrieved in terraform is the simple string : "${CIRCLE_SHA1}".

**Comment by andresrv94** [comment]
I'm having the same issue, I need to use a path with an environment variable and it doesn't interpolate it.

**Comment by sdc-wag** [comment]
Experiencing the same and I'll follow this issue. Hopefully a fix will be made 😊 Thanks for a nice orb either way.

**Comment by gavinclarkeuk** [comment]
Came up with a reasonable workaround for this issue, by adding a job that writes a tfvars file from the env vars, and passing that through to the terraform jobs.

```
jobs:
  write-tf-vars:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "db_user=\"${DB_USER}\"" >> env.tfvars
      - run: echo "db_password=\"${DB_PASSWORD}\"" >> env.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - env.tfvars

workflows:
  main:
    jobs:
      - write-tf-vars
      - terraform/plan:
          checkout: true
          attach-workspace: true
          workspace-root: terraform
          path: terraform
          var_file: env.tfvars
          requires:
            - write-tf-vars
```

Note that because of https://github.com/CircleCI-Public/terraform-orb/issues/56 if you specify a `path` in the terraform workflow step then you must also set the `workspace-root` to ensure the tfvars file is in a subdirectory of the `path`.
