### ISSUE TITLE
How to read and use azure blob as remote backend. Example needed please

### ISSUE THREAD

**Issue by onenessboy** [CircleCI-Public/terraform-orb#79]
Hi I am trying to use this orb for to create azure infrastructure with terraform. But struggling to find out how to implement azure blob as remote backend . 

Please help with circleci.yml with azure as remote backend

what are variable that I need to need to add in context for this azure remote backend to work ?

**Comment by KyleTryon** [comment]
Hello @onenessboy 
I saw your comment here: https://github.com/CircleCI-Public/terraform-orb/issues/51#issuecomment-1134275857

I believe you are doing everything correctly potentially. It sounds like from the error that maybe you ran the init command but no terraform files were found, you may need to adjust your path.

Take a look here: https://circleci.com/developer/orbs/orb/circleci/terraform#jobs-init

The jobs each have a `path` parameter to point to the TF module. Your error mentions that no tf files were found, this may be because you have them in a sub-directory like `src`.

Here is how we call the TF orb in our own tests.

https://github.com/CircleCI-Public/terraform-orb/blob/81c0aad8108de96562958ddaec486d31ba8da9a6/.circleci/test-deploy.yml#L16

```
- terraform/init:
          path: "src/infra"
```

**Comment by onenessboy** [comment]
> Hello @onenessboy I saw your comment here: [#51 (comment)](https://github.com/CircleCI-Public/terraform-orb/issues/51#issuecomment-1134275857)
> 
> I believe you are doing everything correctly potentially. It sounds like from the error that maybe you ran the init command but no terraform files were found, you may need to adjust your path.
> 
> Take a look here: https://circleci.com/developer/orbs/orb/circleci/terraform#jobs-init
> 
> The jobs each have a `path` parameter to point to the TF module. Your error mentions that no tf files were found, this may be because you have them in a sub-directory like `src`.
> 
> Here is how we call the TF orb in our own tests.
> 
> https://github.com/CircleCI-Public/terraform-orb/blob/81c0aad8108de96562958ddaec486d31ba8da9a6/.circleci/test-deploy.yml#L16
> 
> ```
> - terraform/init:
>           path: "src/infra"
> ```

Hi @KyleTryon Thank you for reply, I am almost given up. Tired in figuring what mistake I am doing...

Here my config file look like:

```
version: 2.1
orbs:
  terraform: circleci/terraform@3.1
  azure-cli: circleci/azure-cli@1.0.0

jobs:
  verify-install:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed
  deploy-azure-infra:    
    executor: terraform/default
    steps:
      - checkout      
      - terraform/init:
          backend: true
          backend_config:
            "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
            storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
            container_name=${TF_CONTAINER_NAME}, \
            key=${TF_KEY_NAME}"
           path: "/Terraform"
      - terraform/plan:          
          backend_config:
            "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
            storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
            container_name=${TF_CONTAINER_NAME}, \
            key=${TF_KEY_NAME}"
          path: "/Terraform"

workflows:
  my-workflow:
    jobs:
      - verify-install        
      - deploy-azure-infra:
          context:
            - ab-synpase
          requires:
           - verify-install

```

My directory structure look like

![image](https://user-images.githubusercontent.com/37249391/169866488-7152a130-66bf-42a6-852a-abe3f5e16bf8.png)


so i have all terrafom file with in this Terraform folder. I am not using any modules

Error I get when I run above (its running on ubuntu machine image)

Path Does not exist.

Can you please help

**Comment by onenessboy** [comment]
> > Hello @onenessboy I saw your comment here: [#51 (comment)](https://github.com/CircleCI-Public/terraform-orb/issues/51#issuecomment-1134275857)
> > I believe you are doing everything correctly potentially. It sounds like from the error that maybe you ran the init command but no terraform files were found, you may need to adjust your path.
> > Take a look here: https://circleci.com/developer/orbs/orb/circleci/terraform#jobs-init
> > The jobs each have a `path` parameter to point to the TF module. Your error mentions that no tf files were found, this may be because you have them in a sub-directory like `src`.
> > Here is how we call the TF orb in our own tests.
> > https://github.com/CircleCI-Public/terraform-orb/blob/81c0aad8108de96562958ddaec486d31ba8da9a6/.circleci/test-deploy.yml#L16
> > 
> > ```
> > - terraform/init:
> >           path: "src/infra"
> > ```
> 
> Hi @KyleTryon Thank you for reply, I am almost given up. Tired in figuring what mistake I am doing...
> 
> Here my config file look like:
> 
> ```
> version: 2.1
> orbs:
>   terraform: circleci/terraform@3.1
>   azure-cli: circleci/azure-cli@1.0.0
> 
> jobs:
>   verify-install:
>     executor: azure-cli/default
>     steps:
>       - azure-cli/install
>       - run:
>           command: az -v
>           name: Verify Azure CLI is installed
>   deploy-azure-infra:    
>     executor: terraform/default
>     steps:
>       - checkout      
>       - terraform/init:
>           backend: true
>           backend_config:
>             "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
>             storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
>             container_name=${TF_CONTAINER_NAME}, \
>             key=${TF_KEY_NAME}"
>            path: "/Terraform"
>       - terraform/plan:          
>           backend_config:
>             "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
>             storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
>             container_name=${TF_CONTAINER_NAME}, \
>             key=${TF_KEY_NAME}"
>           path: "/Terraform"
> 
> workflows:
>   my-workflow:
>     jobs:
>       - verify-install        
>       - deploy-azure-infra:
>           context:
>             - ab-synpase
>           requires:
>            - verify-install
> ```
> 
> My directory structure look like
> 
> ![image](https://user-images.githubusercontent.com/37249391/169866488-7152a130-66bf-42a6-852a-abe3f5e16bf8.png)
> 
> so i have all terrafom file with in this Terraform folder. I am not using any modules
> 
> Error I get when I run above (its running on ubuntu machine image)
> 
> Path Does not exist.
> 
> Can you please help

I made little progress, at least that Path issue gone now I am presented with new issue as below during init

I changed path to 
`path: "Terraform" `

But Now I got another error

`│ Error: Error building ARM Config: Please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH.`

any idea about this.. I have verified azure version is 2.36.0

am i missing any parameters ?

What should be values expected for this  considering i am using azure blob stored remote backend?

![image](https://user-images.githubusercontent.com/37249391/169970805-36bba034-5cd0-4172-aa47-ab9b024e034f.png)

**Comment by onenessboy** [comment]
Now, i get past this error, now it complains TF_PARAM_BACKEND_CONFIG_FILE is not present, i have already created this variable as of part of context. what is expected values for TF_PARAM_BACKEND , TF_PARAM_BACKEND_CONFIG, TF_PARAM_BACKEND,CONFIG_FILE 
, TF_PARAM_CLI_CONFIG_FILE ?

My updated is code below:

```
version: 2.1
orbs:
  terraform: circleci/terraform@3.1
  azure-cli: circleci/azure-cli@1.0.0

jobs:
  verify-install:
    executor: azure-cli/default      
    steps:
      - checkout
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed
      - run: 
          name: Setup Terraform Remote Backend 
          command: |
            az login --service-principal -u $spid -p $spkey --tenant $tenantid
            az group create --location $region --name $terraformstoragerg
            az storage account create --name $terraformstorageaccount --resource-group $terraformstoragerg --location $region --sku Standard_LRS
            az storage container create --name terraform --account-name $terraformstorageaccount
            key=$(az storage account keys list -n $terraformstorageaccount --query [0].value -o tsv)
      - terraform/init:
          backend: true
          backend_config_file: ${TF_PARAM_BACKEND_CONFIG_FILE}
          # backend_config:
          #   "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
          #   storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
          #   container_name=${TF_CONTAINER_NAME}, \
          #   key=${TF_KEY_NAME}"
          path: "Terraform"
          # backend_config_file: "~/Terraform/backend.tf"

      - terraform/plan:          
          backend_config:
            "resource_group_name=${TF_RESOURCE_GROUP_NAME}, \
            storage_account_name=${TF_STORAGE_ACCOUNT_NAME}, \
            container_name=${TF_CONTAINER_NAME}, \
            key=${TF_KEY_NAME}"
          path: "Terraform"  

workflows:
  my-workflow:
    jobs:
      - verify-install:
          context:
             - ab-synpase     


```

I really confused what will work what variable is needed what should be values for those etc
