### ISSUE TITLE
BASH_ENV variables not passed through to orb

### ISSUE THREAD

**Issue by jamesaspence** [CircleCI-Public/terraform-orb#83]
**Orb Version**
3.1

**Describe the bug**

In our circleCI build, I am attempting to push an env variable with an image tag into `BASH_ENV`, but the value gets lost in between the steps of the job. For example, I'm trying to do something like this: https://circleci.com/docs/env-vars#example-configuration-of-environment-variables. However, the only env variables available within the orb's steps are variables set by circleci itself.

I'm not really positive this is a bug report, but it didn't feel like a feature request either. I believe I'm likely misunderstanding something about the config that needs to change, but I'm hoping if nothing else I might get a bit of a nudge in the right direction :)

An example job config:
```
version: '2.1'
orbs:
    terraform: circleci/terraform@3.1
jobs:
  deploy-infrastructure:
    docker:
      - image: hashicorp/terraform:1.1.2
    steps:
      - checkout
      - run:
          name: Set terraform tag
          command: |
            echo "export TERRAFORM_TAG=${CIRCLE_SHA1}" >> $BASH_ENV
            source $BASH_ENV
            echo "Deploying image tag '${TERRAFORM_TAG}' via terraform."
      - terraform/fmt:
          path: ./deployment/terraform
      - terraform/validate:
          path: ./deployment/terraform
      - terraform/init:
          path: ./deployment/terraform
      - terraform/plan:
          path: ./deployment/terraform
          var: "image_tag=${TERRAFORM_TAG}"
      - terraform/apply:
          path: ./deployment/terraform
          var: "image_tag=${TERRAFORM_TAG}"
```

in the above example, the value of `TERRAFORM_TAG` is lost after the `run` step, and ends up empty.

As a workaround, I have configured circleci to manually run the commands like this:
```
version: '2.1'
orbs:
    terraform: circleci/terraform@3.1
jobs:
  deploy-infrastructure:
    docker:
      - image: hashicorp/terraform:1.1.2
    steps:
      - checkout
      - run:
          name: Set terraform tag
          command: |
            echo "export TERRAFORM_TAG=${CIRCLE_SHA1}" >> $BASH_ENV
            source $BASH_ENV
      - terraform/fmt:
          path: ./deployment/terraform
      - terraform/validate:
          path: ./deployment/terraform
      - run:
          name: Deploy via terraform
          command: |
            source $BASH_ENV
            echo "Deploying image tag '${TERRAFORM_TAG}' via terraform."
            terraform -chdir=./deployment/terraform init -input=false -backend=true
            terraform -chdir=./deployment/terraform plan -input=false -out=plan.out -var="image_tag=${TERRAFORM_TAG}"
            terraform -chdir=./deployment/terraform apply -input=false -auto-approve -var="image_tag=${TERRAFORM_TAG}"
```

**To Reproduce**

1. Set up a configuration like the above example, where an environment variable is saved to `BASH_ENV`
2. Attempt to access that value inside a followup step within the same job
3. Confirm that the BASH_ENV variable is not available as expected

**Expected behavior**

That BASH_ENV would be sourced into the terraform orb and variables would also be accessible within the orb's command contexts as well.

**Additional context**
