### ISSUE TITLE
Add Terraform parallelism option on apply

### ISSUE THREAD

**Issue by apanchev** [CircleCI-Public/terraform-orb#88]
**Is your feature request related to a problem? Please describe:**

In some projects with specific Terraform version i need to be able to set terraform parallelism parameter. 

**Describe the solution you'd like:**

Just need the parallelism parameter to be available in command/job definition.
```
# Simple use case example: 

- terraform/apply:
    attach-workspace: true
    backend_config_file: backend.hcl
    path: ./terraform
    plan: ./plan.out
    parallelism: 1
```

Would be happy to submit a PR
